### ISSUE TITLE
inconsistent sequence recovery between model.pt provided and that self-trained

### ISSUE THREAD

**Issue by sqliu2016** [BytedProtein/ByProt#10]
hey, we have trained the example1 [[_Example 1: Non-autoregressive (NAR) ProteinMPNN baseline]_ using the code as provided on GPU v-100，and successfully got the model.pt file after 10h training.

However, in sequence prediction with the code provided in example 1 [_Example 1: ProteinMPNN-CMLM_], we found the trained model gave  inconsistent sequence recovery with the model you provided.  just like this:

provided model:
(ByProt) ubuntu@VM-4-3-ubuntu:~/software/ByProt$ python example1.py
Restored from /home/ubuntu/software/ByProt/protein_mpnn_cmlm/checkpoints/best.ckpt with 0 missing and 0 unexpected keys
loading backbone structure from /home/ubuntu/software/ByProt/data/5L33/5L33.pdb.
prediction: MVPPEEEVAEELIEALEDGDPELAEEVLTPDARFVFNGETFTGPELEEFVEELAEDGLRFRPVSGSVVGDYFVFTVVVESDGETRTFRFRFRVENGRLEELRFEST
recovery: 0.3584905660377358

self-trained model

(ByProt) ubuntu@VM-4-3-ubuntu:~/software/ByProt$ python example1-GPU-train.py
Restored from /home/ubuntu/software/ByProt/GPU-logs/fixedbb/cath_4.2/protein_mpnn_cmlm/checkpoints/best.ckpt with 0 missing and 0 unexpected keys
loading backbone structure from /home/ubuntu/software/ByProt/data/5L33/5L33.pdb.
prediction: SMPIDELVASKFIKALEKNDPELMAKVITPDTKLEWNGKKYKGEEIVEFVEEIKKSGTKFKLLSYKKVGNEYVFDVTVSNNGETRNATVTIEVKNGKIDFVNITCH
recovery: 0.5188679245283019

So what is the possible reason of the  inconsistent results?

**Comment by zhengzx-nlp** [comment]
hi @sqliu2016, you're right, it seems that I uploaded a wrong checkpoint for ProtMPNN-CMLM. The result from your self-trained model should be correct. I will replace the ckpt very soon. Many thanks for letting me know!

**Comment by sqliu2016** [comment]
@zhengzx-nlp Thanks a lot !!

**Comment by sqliu2016** [comment]
@zhengzx-nlp Thanks a lot !!

**Comment by zhengzx-nlp** [comment]
hi @sqliu2016 I've updated pretrained weights. please give it a try.
