### ISSUE TITLE
Fine tuning on custom data

### ISSUE THREAD

**Issue by BSharmi** [BytedProtein/ByProt#11]
Hi there!
Is there a data preparation script that I can use to fine tune LM-Design on a custom set of pdb files? So far I had just been using the CATH datasets with has the json and jsonl files already preprocessed. I wanted to know how to create these files if I had a custom set of pdb files. It would be really helpful to format and fine tune the model.

Thank you very much!

**Comment by YifanDengWHU** [comment]
Hi,
In order to extract the data from pdb file, you need to extract the coordinates of the  N, Cα, C, O atoms of each residue. 
The key code will be like:
```
from Bio.PDB import PDBParser
parser = PDBParser()

structure = parser.get_structure('MyProtein', 'myprotein.pdb')

for model in structure:
    for chain in model:
        for residue in chain:
            for atom in residue:
                if atom.get_name() in ['N', 'CA', 'C', 'O']:
                    print(f"Residue: {residue.get_resname()}, Atom: {atom.get_name()}, Coordinates: {atom.get_coord()}")
```

**Comment by BSharmi** [comment]
Awesome thank you so much. I will work with it
