### ISSUE TITLE
Masking on inpaint task 

### ISSUE THREAD

**Issue by BSharmi** [BytedProtein/ByProt#12]
Hi there!

Thanks for adding the inpaint task! For this task are all tokens in the inpaint region masked by default? How do we provided masked  coordinates for an inpaint task? 

From what I understood the initialization always happens from full masked region, 
the function (https://github.com/BytedProtein/ByProt/blob/main/src/byprot/tasks/fixedbb/designer.py#L25)  does not consider `coord_mask` to generate previous tokens

```
target_mask = (
        target_tokens.ne(alphabet.padding_idx)  # & mask
        & target_tokens.ne(alphabet.cls_idx)
        & target_tokens.ne(alphabet.eos_idx)
    )
_tokens = target_tokens.masked_fill(
        target_mask, alphabet.mask_idx
    )
```

and the initialization happens with full mask 
(https://github.com/BytedProtein/ByProt/blob/main/src/byprot/models/fixedbb/generator.py#L74)
`initial_output_tokens, initial_output_scores = model.initialize_output_tokens(
            batch, encoder_out=encoder_out)`

But I could have missed something in between.

If you could please clarify/provide an example that would be awesome!

Thank you!

**Comment by zhengzx-nlp** [comment]
Here for inpainting task, **coordinates** for inpaint region are supposed to be remain unmodified and will not be modified (so we should no twist `coord_mask`, which is used to indicate whether the provided coordinates of a residue are valid/not `nan`) . So for those normal cases where coordinates are valid, including inpainting , `coord_mask` should always be `true`. 

Those various masking strategies are only used to setup `prev_token_mask` for initializing **tokens**. For example, the following code only take `batch['prev_token_mask']
```python
initial_output_tokens, initial_output_scores = model.initialize_output_tokens(
        batch, encoder_out=encoder_out)
```
where `model.initialize_output_tokens(batch, encoder_out=encoder_out)` for `ESM2Adapter` 
https://github.com/BytedProtein/ByProt/blob/b94ba12f496d0b6b7c66b67a4ab02a68b46d5679/src/byprot/models/fixedbb/lm_design/esm2_adapter.py#L121-L122

**Comment by BSharmi** [comment]
Thank you so much for explaining! Does that mean for inpainting we cannot keep some amino acids fixed and by default the entire region is considered for rewriting with full mask?

**Comment by BSharmi** [comment]
I figured out how to mask the inpaint region by adding arguments to the inpaint function. Closing the issue, thank you
