### ISSUE TITLE
no module esm？

### ISSUE THREAD

**Issue by Mistletoe-git** [BytedProtein/ByProt#26]
please help me...

**Comment by zhengzx-nlp** [comment]
hi could you please share your running logs? How did you install the repo? That may help locate the problem.

**Comment by Mistletoe-git** [comment]
谢谢兄弟，已经解决了。

**Comment by gitzlc** [comment]
> 谢谢兄弟，已经解决了。

老哥，我也遇到No module named 'esm'了，并且python3.7时装esm时找不到对应的版本，能问下你是怎么解决的吗

**Comment by Mistletoe-git** [comment]
> > 谢谢兄弟，已经解决了。
> 
> 老哥，我也遇到No module named 'esm'了，并且python3.7时装esm时找不到对应的版本，能问下你是怎么解决的吗

你好哥们，这个repo使用的esm模块(不是ESM3)需要使用`pip install fair-esm`进行安装，你可能把fair-esm误写成esm了，然后我通常是在python-3.10安装这个模块进行使用，具体可以参考ESM的官方文档：https://github.com/facebookresearch/esm
希望可以帮助到你！
