### ISSUE TITLE
Download CATH4.3 returns accessdenied

### ISSUE THREAD

**Issue by realfenston** [BytedProtein/ByProt#5]
Hello,

When I am downloading the CATH4.3 dataset following instructions in your script, it runs normally to download the chain_set.jsonl file while returns an accessdenied error in the following link https://dl.fbaipublicfiles.com/fair-esm/data/cath4.3_topologysplit_202206/split.jsonl. Would you mind checking the issue or providing an alternative download source?

Much appreciation in advance.

**Comment by zhengzx-nlp** [comment]
Hi @realfenston, thank you for reporting this issue. I'll check the original url later. 

I have uploaded CATH data to google drive at this: [cath data](https://drive.google.com/file/d/1zFMpx-m9QTi-ykBJgavZZCMvynsF5E1D/view?usp=sharing). Please have a try.

Best,
Zaxiang

**Comment by realfenston** [comment]
Thanks a lot for your reply!
