### ISSUE TITLE
weight

### ISSUE THREAD

**Issue by leobince** [BytedProtein/ByProt#7]
sorry.  is the trained weight provided, or we have to train the model by ourselves.

**Comment by Z-MU-Z** [comment]
same question!

**Comment by zhengzx-nlp** [comment]
Hello @leobince @Z-MU-Z, thank you for your interest in our work! As for your question, I will be working on providing model weights in an easier way shortly. Plus, reproducing model training should also be fairly easy and and we warmly encourage you to also have a try. 😊

Zaixiang

**Comment by BSharmi** [comment]
Hey Zaixiang!

I had the same question! I will try to train the model. But it would be super helpful if we have the weights as well :) 

Thank you!

**Comment by BSharmi** [comment]
Actually I was able to train the model on CATH4.2!

**Comment by zhengzx-nlp** [comment]
Hey everyone seeing this thread, I have updated readme to include links to pretrained model weights. If there are any problems, please feel free to let me know!

Best
Zaixiang

**Comment by benyaminjami** [comment]
Hi Zaixiang,
Thank you for the update. Are you going to release the weights for the multichain dataset? I was going to train the model myself, but considering the dataset size, I may be unable to do it.

**Comment by BSharmi** [comment]
Hey Zaixiang!

Thanks so much for providing the weights. I noticed that the zip files had the weights but not the `.yaml` files which are needed to load the trained model. Is that something in another folder?

Thank you!

**Comment by zhengzx-nlp** [comment]
hi @BSharmi, actually it should have the yaml file but in `.hydra` folder which is invisible to GUI. 

<img width="782" alt="image" src="https://github.com/BytedProtein/ByProt/assets/29270238/fd5d8f3b-5fb0-4338-8652-ebe664a6699d">

**Comment by zhengzx-nlp** [comment]
Hi @benyaminjami. I will upload the model weights for `multichain` shortly. I also needed to retrain ones to ensure the models got fully tested before uploading. Thank you for your interest!
> Hi Zaixiang, Thank you for the update. Are you going to release the weights for the multichain dataset? I was going to train the model myself, but considering the dataset size, I may be unable to do it.

**Comment by BSharmi** [comment]
gotcha thank you!

**Comment by zhengzx-nlp** [comment]
Hi @benyaminjami I've uploaded the pretrained weight for `lm_design_esm2_650m` for `multichain` dataset. Please give it a try!
